project:
  type: website
  output-dir: docs

website:
  title: "JessicaLin92.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - text: Project
        menu: 
        - href: Data Viz.qmd
          text: Data Visualization 
        - href: Text-Analysis.qmd
          text: Text Analysis
        - href: Simulation.qmd
          text: Simulation
        - href: SQL.qmd
          text: SQL 
        

format:
  html:
    theme: minty
    css: styles.css
    toc: true

editor: visual

