project:
  type: website
  output-dir: docs

website:
  title: "JessicaLin92.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - text: Data Science Project
        menu: 
        - href: Data Viz.qmd
          text: Project 1-Data Visualization 
        - href: Text-Analysis.qmd
          text: Project 2-Text Analysis
        - href: Simulation.qmd
          text: Project 3-Simulation
        - href: SQL.qmd
          text: Project 4-SQL 
      - href: Presentation.qmd
        text: Presentattion
      

        

format:
  html:
    theme: minty
    css: styles.css
    toc: true

editor: visual

