project:
  type: website
  output-dir: docs

website:
  title: "JessicaLin92.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - Data Viz.qmd

format:
  html:
    theme: minty
    css: styles.css
    toc: true

editor: visual

