# Shiny App - ExtraCredit

This is a Rock Paper Scissor Game for my Extra Credit Shiny project

```{r}
library(shiny)

# Define your UI
ui <- fluidPage(
  titlePanel("Rock-Paper-Scissors Game"),
  sidebarLayout(
    sidebarPanel(
      h3("Choose your move:"),
      radioButtons("user_choice", "Your choice:",
                   choices = list("Rock", "Paper", "Scissors"), 
                   selected = "Rock"),
      actionButton("play", "Play Game")
    ),
    mainPanel(
      h4("Game Result:"),
      textOutput("result"),
      br(),
      textOutput("computer_choice"),
      br(),
      textOutput("score")
    )
  )
)

# Define your server logic
server <- function(input, output, session) {
  score <- reactiveVal(list(user = 0, computer = 0))
  computer_choice <- function() {
    sample(c("Rock", "Paper", "Scissors"), 1)
  }
  
  determine_winner <- function(user, computer) {
    if (user == computer) {
      return("It's a tie!")
    }
    if ((user == "Rock" && computer == "Scissors") ||
        (user == "Paper" && computer == "Rock") ||
        (user == "Scissors" && computer == "Paper")) {
      return("You win!")
    } else {
      return("Computer wins!")
    }
  }
  
  update_score <- function(winner) {
    current_score <- score()
    if (winner == "You win!") {
      current_score$user <- current_score$user + 1
    } else if (winner == "Computer wins!") {
      current_score$computer <- current_score$computer + 1
    }
    score(current_score)
  }
  
  observeEvent(input$play, {
    user_move <- input$user_choice
    comp_move <- computer_choice()
    game_result <- determine_winner(user_move, comp_move)
    update_score(game_result)
    
    output$result <- renderText({ game_result })
    output$computer_choice <- renderText({ paste("Computer chose:", comp_move) })
    output$score <- renderText({
      paste("Score - You: ", score()$user, " Computer: ", score()$computer)
    })
  })
}

shinyApp(ui = ui, server = server)
